function vn310imu = importimu(filename, dataLines)
%IMPORTFILE Import data from a text file
%  VN310IMU = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  VN310IMU = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  vn310imu = importfile("E:\Studium\M2-Inertialnavigation\Uebung\3\Code\vn310-imu.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2021-07-22 13:55:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 52);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["GpsCycle", "GpsWeek", "GpsTow", "TimeTimeStartup", "TimeGpsTow", "TimeGpsWeek", "TimeTimeStatustimeOk", "TimeTimeStatusdateOk", "TimeTimeStatusutcTimeValid", "IMUUncompMagX", "IMUUncompMagY", "IMUUncompMagZ", "IMUUncompAccelX", "IMUUncompAccelY", "IMUUncompAccelZ", "IMUUncompGyroX", "IMUUncompGyroY", "IMUUncompGyroZ", "IMUTemp", "IMUPres", "IMUDeltaTime", "IMUDeltaThetaX", "IMUDeltaThetaY", "IMUDeltaThetaZ", "IMUDeltaVelX", "IMUDeltaVelY", "IMUDeltaVelZ", "IMUMagX", "IMUMagY", "IMUMagZ", "IMUAccelX", "IMUAccelY", "IMUAccelZ", "IMUAngularRateX", "IMUAngularRateY", "IMUAngularRateZ", "GNSS1Tow", "GNSS1Week", "GNSS1TimeInfoStatustimeOk", "GNSS1TimeInfoStatusdateOk", "GNSS1TimeInfoStatusutcTimeValid", "GNSS1TimeInfoLeapSeconds", "AttYawPitchRollY", "AttYawPitchRollP", "AttYawPitchRollR", "AttQuaternionw", "AttQuaternionx", "AttQuaterniony", "AttQuaternionz", "AttYprUY", "AttYprUP", "AttYprUR"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
vn310imu = readtable(filename, opts);

end